# -*- coding: utf-8 -*-
"""Interior IQ

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cY329UoMPA3M4MujDUrG-tKNMuR6GVUe
"""

!pip install torch torchvision diffusers transformers accelerate opencv-python pillow matplotlib --quiet

import torch
from diffusers import StableDiffusionPipeline
from PIL import Image
import matplotlib.pyplot as plt
from google.colab import files

print("Upload your empty room image:")
uploaded = files.upload()
for fn in uploaded.keys():
    room_path = fn

room_img = Image.open(room_path)
plt.imshow(room_img)
plt.axis('off')
plt.title("Uploaded Empty Room")
plt.show()

print("Please enter the following details for design generation:")

room_type = input("Room Type (e.g., Living Room, Master Bedroom, Kitchen): ").strip()
budget_inr = input("Budget in INR (e.g., 50000): ").strip()
style = input("Design Style (Modern, Minimalist, Traditional): ").strip()
lighting = input("Lighting Preference (Warm, Bright, Natural, Dim): ").strip()
num_variations = input("Number of design variations to generate (e.g., 3): ").strip()
num_variations = int(num_variations)

budget_int = int(budget_inr)
if budget_int < 50000:
    budget_desc = "affordable furniture, budget-friendly design"
elif budget_int < 200000:
    budget_desc = "moderate furniture, stylish yet budget-conscious"
else:
    budget_desc = "luxurious furniture, premium materials"

print("Loading AI model (this may take a minute)...")
device = "cuda" if torch.cuda.is_available() else "cpu"

pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16 if device=="cuda" else torch.float32
)
pipe = pipe.to(device)

base_prompt = f"Interior design of an empty {room_type} in {style} style with {lighting} lighting, furniture and decoration arranged according to Vastu principles, {budget_desc}, realistic photo, 3D perspective"
print("\nBase AI Prompt:\n", base_prompt)

generated_images = []
print(f"\nGenerating {num_variations} interior design variations... This may take a few minutes depending on GPU/CPU.")

for i in range(num_variations):
    print(f"Generating variation {i+1}...")
    img = pipe(base_prompt, height=512, width=512).images[0]
    generated_images.append(img)

plt.figure(figsize=(15, 5))
for idx, img in enumerate(generated_images):
    plt.subplot(1, num_variations, idx+1)
    plt.imshow(img)
    plt.axis('off')
    plt.title(f"Variation {idx+1}")
plt.show()

for idx, img in enumerate(generated_images):
    filename = f"interior_design_variation_{idx+1}.png"
    img.save(filename)
    files.download(filename)